In [8]:
!pip install serpapi pandas dotenv pydantic google-genai

Requirement already satisfied: serpapi in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (1.0.2)
Requirement already satisfied: pandas in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (3.0.2)
Requirement already satisfied: dotenv in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (0.9.9)
Requirement already satisfied: pydantic in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (2.13.3)
Collecting google-genai
  Downloading google_genai-1.74.0-py3-none-any.whl.metadata (52 kB)
Requirement already satisfied: requests in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from serpapi) (2.33.1)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: python-dotenv in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from dotenv) (1.2.2)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from pydantic) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from pydantic) (2.46.3)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from pydantic) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from pydantic) (0.4.2)
Collecting anyio<5.0.0,>=4.8.0 (from google-genai)
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting google-auth<3.0.0,>=2.48.1 (from google-auth[requests]<3.0.0,>=2.48.1->google-genai)
  Downloading google_auth-2.50.0-py3-none-any.whl.metadata (6.2 kB)
Collecting httpx<1.0.0,>=0.28.1 (from google-genai)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting tenacity<9.2.0,>=8.2.3 (from google-genai)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting websockets<17.0,>=13.0.0 (from google-genai)
  Using cached websockets-16.0-cp314-cp314-win_amd64.whl.metadata (7.0 kB)
Collecting distro<2,>=1.7.0 (from google-genai)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting sniffio (from google-genai)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: idna>=2.8 in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.13)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai)
  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=38.0.3 (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai)
  Downloading cryptography-47.0.0-cp311-abi3-win_amd64.whl.metadata (4.5 kB)
Requirement already satisfied: certifi in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.4.22)
Collecting httpcore==1.* (from httpx<1.0.0,>=0.28.1->google-genai)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from requests->serpapi) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from requests->serpapi) (2.6.3)
Collecting cffi>=2.0.0 (from cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai)
  Using cached cffi-2.0.0-cp314-cp314-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai)
  Using cached pyasn1-0.6.3-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\kuchbhe\Desktop\Travelara-ai\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading google_genai-1.74.0-py3-none-any.whl (790 kB)
   ---------------------------------------- 0.0/790.4 kB ? eta -:--:--
   ---------------------------------------- 790.4/790.4 kB 7.7 MB/s  0:00:00
Using cached anyio-4.13.0-py3-none-any.whl (114 kB)
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Downloading google_auth-2.50.0-py3-none-any.whl (246 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Using cached websockets-16.0-cp314-cp314-win_amd64.whl (178 kB)
Downloading cryptography-47.0.0-cp311-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ------------------- -------------------- 1.8/3.8 MB 9.0 MB/s eta 0:00:01
   --------------------------------- ------ 3.1/3.8 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 7.2 MB/s  0:00:00
Using cached cffi-2.0.0-cp314-cp314-win_amd64.whl (185 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Using cached pyasn1-0.6.3-py3-none-any.whl (83 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Installing collected packages: websockets, tenacity, sniffio, pycparser, pyasn1, h11, distro, anyio, pyasn1-modules, httpcore, cffi, httpx, cryptography, google-auth, google-genai

   ----------------------------------------  0/15 [websockets]
   ----------------------------------------  0/15 [websockets]
   ----------------------------------------  0/15 [websockets]
   ----------------------------------------  0/15 [websockets]
   ----------------------------------------  0/15 [websockets]
   -- -------------------------------------  1/15 [tenacity]
   -- -------------------------------------  1/15 [tenacity]
   ----- ----------------------------------  2/15 [sniffio]
   -------- -------------------------------  3/15 [pycparser]
   ---------- -----------------------------  4/15 [pyasn1]
   ---------- -----------------------------  4/15 [pyasn1]
   ---------- -----------------------------  4/15 [pyasn1]
   ---------- -----------------------------  4/15 [pyasn1]
   ------------- --------------------------  5/15 [h11]
   ------------- --------------------------  5/15 [h11]
   ---------------- -----------------------  6/15 [distro]
   ------------------ ---------------------  7/15 [anyio]
   ------------------ ---------------------  7/15 [anyio]
   ------------------ ---------------------  7/15 [anyio]
   ------------------ ---------------------  7/15 [anyio]
   ------------------ ---------------------  7/15 [anyio]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   --------------------- ------------------  8/15 [pyasn1-modules]
   ------------------------ ---------------  9/15 [httpcore]
   ------------------------ ---------------  9/15 [httpcore]
   ------------------------ ---------------  9/15 [httpcore]
   -------------------------- ------------- 10/15 [cffi]
   -------------------------- ------------- 10/15 [cffi]
   ----------------------------- ---------- 11/15 [httpx]
   ----------------------------- ---------- 11/15 [httpx]
   ----------------------------- ---------- 11/15 [httpx]
   ----------------------------- ---------- 11/15 [httpx]
   ----------------------------- ---------- 11/15 [httpx]
   -------------------------------- ------- 12/15 [cryptography]
   -------------------------------- ------- 12/15 [cryptography]
   -------------------------------- ------- 12/15 [cryptography]
   -------------------------------- ------- 12/15 [cryptography]
   -------------------------------- ------- 12/15 [cryptography]
   -------------------------------- ------- 12/15 [cryptography]
   -------------------------------- ------- 12/15 [cryptography]
   -------------------------------- ------- 12/15 [cryptography]
   -------------------------------- ------- 12/15 [cryptography]
   ---------------------------------- ----- 13/15 [google-auth]
   ---------------------------------- ----- 13/15 [google-auth]
   ---------------------------------- ----- 13/15 [google-auth]
   ---------------------------------- ----- 13/15 [google-auth]
   ---------------------------------- ----- 13/15 [google-auth]
   ---------------------------------- ----- 13/15 [google-auth]
   ---------------------------------- ----- 13/15 [google-auth]
   ---------------------------------- ----- 13/15 [google-auth]
   ---------------------------------- ----- 13/15 [google-auth]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ------------------------------------- -- 14/15 [google-genai]
   ---------------------------------------- 15/15 [google-genai]

Successfully installed anyio-4.13.0 cffi-2.0.0 cryptography-47.0.0 distro-1.9.0 google-auth-2.50.0 google-genai-1.74.0 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 pyasn1-0.6.3 pyasn1-modules-0.4.2 pycparser-3.0 sniffio-1.3.1 tenacity-9.1.4 websockets-16.0

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import pandas as pd
with open(r"C:\Users\kuchbhe\Desktop\Travelara-ai\backend\tests\pipeline_test\data\cities15000\cities15000.txt", "r", encoding="utf-8") as f:
    cities_data = f.read().splitlines()
cities_data

["3040051\tles Escaldes\tles Escaldes\tEhskal'des-Ehndzhordani,Ehskal'des-Ehngordani,Escaldes,Escaldes-Engordany,Les Escaldes,aisakaladesa-inagoradani,askalds-angwrdany,askalds-anګwrdany,askaldys-anjwrdany,askalڈs-angwrڈany,esakaladesa-enagordani,eskaladesa-enagordani,esukarudesu=engorudani jiao qu,lai sai si ka er de-en ge er da,ʿisikaልdesi-ʿenigoridani,Эскальдес-Энгордани,Эскальдес-Энджордани,إسكالديس-إنجورداني,اسکالدس-انګوردانی,اسکالدس-انگوردانی,اسکالڈس-انگورڈانی,एस्कलडेस-एनगोर्डानी,এসকালডেস-এনগোর্ডানি,ਐਸਕਾਲਡੇਸ-ਇਨਗੋਰਡਾਨੀ,ኢስካልዴስ-ኤንጎርዳኒ,エスカルデス＝エンゴルダニ教区,萊塞斯卡爾德-恩戈爾達,萊塞斯卡爾德－恩戈爾達\t42.50729\t1.53414\tP\tPPLA\tAD\t\t08\t\t\t\t15853\t\t1033\tEurope/Andorra\t2026-04-13",
 "3041563\tAndorra la Vella\tAndorra la Vella\tALV,Ando-la-Vyey,Andora,Andora la Vela,Andora la Velja,Andora lja Vehl'ja,Andoro Malnova,Andorra,Andorra Tuan,Andorra a Vella,Andorra la Biella,Andorra la Vella,Andorra la Vielha,Andorra-a-Velha,Andorra-la-Vel'ja,Andorra-la-Vielye,Andorre-la-Vieille,Andò-la-Vyèy,Andòrra la Vièlha,an dao er cheng,andolalabeya,andwra la fyla,Ανδόρρα,Андора ла Веля,Андора ла Веља,Андора ля Вэлья,Андорра-ла-Велья,אנדורה לה וולה,أندورا لا فيلا,አንዶራ ላ ቬላ,アンドラ・ラ・ヴェリャ,安道爾城,안도라라베야\t42.50779\t1.52109\tP\tPPLC\tAD\t\t07\t\t\t\t20430\t\t1037\tEurope/Andorra\t2020-03-03",
 '290503\tWarīsān\tWarisan\tWarisan,Warsan,Warīsān,wrsan,ورسان\t25.16744\t55.40708\tP\tPPL\tAE\t\t03\t\t\t\t108759\t\t12\tAsia/Dubai\t2024-06-11',
 '290581\tUmm Suqaym\tUmm Suqaym\tUmm Suqaym,Umm Suqeim,Umm Suqeim 2,Umm as Suqaym,am sqym,أم سقيم\t25.15491\t55.21015\tP\tPPLX\tAE\t\t03\t\t\t\t16459\t\t1\tAsia/Dubai\t2024-10-28',
 "290594\tUmm Al Quwain City\tUmm Al Quwain City\tOumm al Qaiwain,Oumm al Qaïwaïn,Um al Kawain,Um al Quweim,Umm Al Quwain,Umm Al Quwain City,Umm al Qaiwain,Umm al Qawain,Umm al Qaywayn,Umm al-Quwain,Umm-al'-Kuvejn,Umm-al'-Kˌuvajn,Umm-ehl'-Kajvajn,Umm-əl-Kˌuvajn,Umm-əl-Kˌuvejn,Yumul al Quwain,am alqwyn,am alqywn,am alqywyn,mdynt am alqywyn,um'ma ala ku'oya'ina,um'ma ala quvaina,uma ala kuvaina,unmu・aru・kaiwain,ʿoም ʿeል ቁwayini,Умм-аль-Кувейн,Умм-аль-Қувайн,Умм-эль-Кайвайн,Умм-әл-Қувайн,Умм-әл-Қувейн,أم القيوين,ام القوین,ام القيوين,ام القیون,مدينة ام القيوين,उम्म अल क़ुवैन,উম্ম আল কুওয়াইন,ਉੰਮ ਅਲ ਕੁਵੈਨ,ኦም አል ቁዋይን,ウンム・アル・カイワイン\t25.56473\t55.55517\tP\tPPLA\tAE\t\t07\t\t\t\t59098\t\t2\tAsia/Dubai\t2026-04-13",
 '290680\tŢarīf Kalbā\tTarif Kalba\tTarif Kalba,Ţarīf Kalbā\t25.0695\t56.33115\tP\tPPL\tAE\t\t04\t\t\t\t51000\t\t10\tAsia/Dubai\t2025-04-17',
 '291061\tAr Rāshidīyah\tAr Rashidiyah\tAl Rashidiya,Ar Rashidiyah,Ar Rāshidīyah,Rashdia,Rashidiyah,Rashīdīyah,alrashdyt,الراشدية\t25.22499\t55.38947\tP\tPPLX\tAE\t\t03\t\t\t\t38425\t\t10\tAsia/Dubai\t2024-10-28',
 "291074\tRas Al Khaimah\tRas Al Khaimah\tJulfa,Khaimah,RAK City,RKT,Ra's al Khaymah,Ra's al-Chaima,Ras Al Khaimah,Ras Al Khaimah City,Ras al Hajma,Ras al Khaimah,Ras al-Chajma,Ras al-Hajma,Ras al-Khaimah,Ras el Khaimah,Ras el Khajma,Ras el Khaïmah,Ras el-Kheima,Ras Əl-Xayma,Ras-al'-Khajma,Ras-ehl'-Khajma,Ras-el'-Khajma,Ras-əl-Khajma,Ra’s al Khaymah,Ra’s al-Chaima,Resue'l-Hayme,Resü'l-Hayme,ras alkhymh,ras alkhymt,ras alkhymہ,ras ٱlkhaymat,rasa ala kha'imaha,rasa ala khaima,rasa ala khaimaha,rasi ʿeል xayimahi,rasu・aru・haima,rʼs ʼl-h'ymh,Рас ел Хајма,Рас-аль-Хайма,Рас-ель-Хайма,Рас-эль-Хайма,Рас-әл-Хайма,ראס אל-ח'ימה,رأس الخیمه,راس الخيمة,راس الخیمہ,رَأْس ٱلْخَيْمَة,रास अल खैमाह,রাস আল খাইমাহ,ਰਾਸ ਅਲ ਖੈਮਾ,ራስ አል ኃይማህ,ラス・アル・ハイマ\t25.78953\t55.9432\tP\tPPLA\tAE\t\t05\t\t\t\t351943\t\t2\tAsia/Dubai\t2026-04-13",
 "291580\tZayed City\tZayed City\tBid' Zayed,Bid’ Zayed,Madinat Za'id,Madinat Zayid,Madīnat Zāyid,Madīnat Zā’id,Zayed City,mdynt zayd,مدينة زايد\t23.65416\t53.70522\tP\tPPL\tAE\t\t01\t103\t12748055\t\t63482\t\t118\tAsia/Dubai\t2024-03-14",
 "291696\tKhawr Fakkān\tKhawr Fakkan\tFakkan,Fakkān,Khawr Fakkan,Khawr Fakkān,Khawr al Fakkan,Khawr al Fakkān,Khor Fakhan,Khor Fakkan,Khor Fakkan City,Khor Fakkān,Khor al Fakhan,Khor al Fakkan,Khor al Fākhān,Khor'fakkan,Khor-Fakkan,Khorfakan,Khorfakhan,Port Khor Fakkan,mdynt khwr fkan,Хор-Факкан,مدينة خور فكان\t25.33132\t56.34199\tP\tPPL\tAE\t\t06\t\t\t\t40677\t\t20\tAsia/Dubai\t2024-09-12",
 '291763\tKalbā\tKalba\tGhalla,Ghallah,Ghālla,Ghāllah,Kalba,Kalbah,Kalbā,Qalba\t25.0513\t56.35422\tP\tPPL\tAE\t\t06\t\t\t\t37545\t\t15\tAsia/Dubai\t2024-10-17',
 '291775\tJumayrā\tJumayra\tJimeirah,Jumaira,Jumairah,Jumayra,Jumayrah,Jumayrā,Jumeira,Jumeirah,jmyra,جميرا\t25.20795\t55.24969\tP\tPPLX\tAE\t\t03\t\t\t\t39080\t\t5\tAsia/Dubai\t2024-04-03',
 "292223\tDubai\tDubai\tDXB,Dabei,Dibai,Dibay,Doubayi,Dubae,Dubai,Dubai City,Dubai emiraat,Dubaija,Dubaj,Dubajo,Dubajus,Dubay,Dubayy,Dubaï,Dubái,Dúbæ,Fort Dabei,Ntoumpai,dby,dbyy,di bai,dobai,du bai,duba'i,dubai,dubay,dube,dubi,dwbyy,tupai,Ντουμπάι,Дубаи,Дубай,Դուբայ,דובאי,דוביי,دبئی,دبى,دبي,دبی,دوبەی,دۇبائى,दुबई,দুবাই,ਦੁਬਈ,துபை,దుబాయ్,ದುಬೈ,ദുബായ്,ดูไบ,დუბაი,ዱቤ,ドバイ,杜拜,迪拜,두바이\t25.07725\t55.30927\tP\tPPLA\tAE\t\t03\t\t\t\t3790000\t\t24\tAsia/Dubai\t2026-04-13",
 '292231\tDibba Al-Fujairah\tDibba Al-Fujairah\tAl-Fujairah,BYB,Dibba Al-Fujairah,dba alfjyrt,دبا الفجيرة\t25.59246\t56.26176\tP\tPPL\tAE\t\t04\t\t\t\t30000\t\t16\tAsia/Dubai\t2014-08-12',
 "292239\tDibba Al-Hisn\tDibba Al-Hisn\tBYB,Daba,Daba al-Hisn,Dabā,Dabā al-Ḥiṣn,Diba,Diba Al Hisn,Diba al Hisn,Dibah,Dibba,Dibba Al Hisn,Dibba Al'-Khisn,Dibba Al-Hisn,Dibbah,Dibbā Al Ḩişn,Dibā,Dibā Al Ḩişn,Dībā al Ḩişn,Hisn Diba,Husn Dibba,Дибба Аль-Хисн,Ḩişn Dibā\t25.61955\t56.27291\tP\tPPL\tAE\t\t04\t\t\t\t26395\t\t4\tAsia/Dubai\t2024-07-14",
 '292261\tDayrah\tDayrah\tDaira,Dairah,Dayrah,Deira,Dirah,Dīrah,dyrt,ديرة\t25.27143\t55.30207\tP\tPPLX\tAE\t\t03\t\t\t\t400000\t\t10\tAsia/Dubai\t2024-10-28',
 "292672\tSharjah\tSharjah\tAl Sharjah,Ash 'Mariqah,Ash Shariqa,Ash Shariqah,Ash Shāriqa,Ash Shāriqah,Ash ’Mariqah,Ash-Shariqah emiraat,Ash-Shāriqah emiraat,Charjah,Ch·ardj·a,SHJ,Sardza,Sardzsa,Sarika,Sarja,Sarjo,Sarza,Schardscha,Shardza,Shardzha,Shardzha kuorat,Sharga,Sharijah,Shariqah,Sharja,Sharjah,Sharjah city,Shārijah,Shāriqah,Shārja,Szardza,Szardża,Xarja,Xarjah,alsharqt,amart alsharqt,carja,charc ah,mdynt alsharqt,saraja,sarajaha,sarja,sharija,sharja,sharjh,sharuja,syaleuja,sʼrgh,xia er jia,Ŝarĵo,Şarika,Şarja,Šardža,Šardžá,Шарджа,Шарджа куорат,Шарџа,Шарҗә,Շարժա,שארגה,إمارة الشارقة,الشارقة,شارجه,شارجہ,مدينة الشارقة,शारजा,शारजाह,শারজাহ,ਸ਼ਾਰਜਾ,சார்ஜா,షార్జా,ಶಾರ್ಜ,ഷാർജ,ชาร์จาห์,შარჯა,ሻርጃ,シャールジャ,夏尔迦,샤르자\t25.3342\t55.41221\tP\tPPLA\tAE\t\t06\t\t\t\t1800000\t\t15\tAsia/Dubai\t2026-04-13",
 "292688\tAr Ruways\tAr Ruways\tAr Ru'ays,Ar Ruways,Ar Ru’ays,Ar-Ruvais,Ruwais,alrwys,ar-Ruways,lu wa si,ruvais,Ар-Руваис,الرويس,الرویس,റുവൈസ്,魯瓦斯,鲁瓦斯\t24.11028\t52.73056\tP\tPPL\tAE\t\t01\t103\t12748114\t\t25000\t\t16\tAsia/Dubai\t2024-03-14",
 '292862\tḨattā\tHatta\tAl Hagarein,Al Hajarayn,Al Ḥagarein,Al Ḩajarayn,Hajarain,Hajarayn,Hajrain,Hatta,hta,حتا,Ḩajarayn,Ḩattā\t24.80073\t56.12726\tP\tPPL\tAE\t\t03\t800\t891\t\t15324\t335\t331\tAsia/Dubai\t2024-10-03',
 "292878\tFujairah\tFujairah\tAl Fujairah City,Al Fujayrah,Al-Fudjayra,Al-Fujayrah' emiraat,El'-Fudzhajra,FJR,Fudschaira,Fudzajra,Fudzejra,Fudzhejra,Fudżajra,Fudžajra,Fueceyre,Fueceyrə,Fujaira,Fujairah,Fujajro,Fujayrah,Fuzhajra,Fuĵajro,Füceyre,Füceyrə,alfjyrt,fjyrh,fjyrt,fjyrہ,fu ji la,fujaira,mdynt alfjyrt,phuja'ira,phujaira,phujairaha,pwg'yyrh,Ель-Фуджайра,Фуджейра,Фужайра,Фуџејра,פוג'יירה,الفجيرة,فجيرة,فجيره,فجیره,فجیرہ,مدينة الفجيرة,फुजैराह,ফুজাইরা,ਫੁਜੈਰਾ,ፉjayira,ፉጃይራ,フジャイラ,富吉拉\t25.11641\t56.34141\tP\tPPLA\tAE\t\t04\t\t\t\t118933\t\t15\tAsia/Dubai\t2026-04-13",
 "292913\tAl Ain City\tAl Ain City\tAAN,Ainas,Al Ain,Al Ain City,Al Ajn,Al Ayn,Al `Ayn,Al Ɛayn,Al ‘Ayn,Al-Ain,Al-Ajn,Al-Ayin,Al-Ayn,Al-Aïn,Ehl'-Ajn,El Ain,El-Ajn,ai yin,al ain,al-ain,al-aini,alʿyn,ela ena,mdynt alʿyn,Ел Аин,Эль-Айн,Ալ-Ային,אל-עין,العين,العین,مدينة العين,एल एन,அல் ஐன்,അൽ ഐൻ,ალ-აინი,アル・アイン,艾因,알아인\t24.19167\t55.76056\tP\tPPL\tAE\t\t01\t102\t\t\t846747\t\t275\tAsia/Dubai\t2024-07-13",
 "292932\tAjman\tAjman\tAcman,Adschman,Adzhman,Adzman,Adżman,Adžman,Ajma,Ajman,Ajman City,Ajmán,Ajmã,Al Ajman,QAJ,Ujman,ajamana,ajman,ajuman,Əcmən,ʻg'mʼn,ʿejamani,ʿjman,ʿyman,Аджман,Аџман,עג'מאן,اجمان,عجمان,عيمان,अजमान,আজমান,ਅਜਮਾਨ,አጃማን,アジュマーン\t25.40177\t55.47878\tP\tPPLA\tAE\t\t02\t\t\t\t490035\t\t2\tAsia/Dubai\t2026-04-13",
 '292953\tAdh Dhayd\tAdh Dhayd\tAdh Dhaid,Adh Dhayd,Adh Dhed,Adh Dhēd,Al Daid,Al-Dhayd,Az-Zajd,Dayd,Dhaid,Dhayd,Duhayd,Ehd-Dajd,Ihaid,Zeyd,adh-Dhayd,aldhyd,da yi de,daid,dhyd,Эд-Дайд,الذيد,ذید,ദൈദ്,Ḑayd,達伊德\t25.28812\t55.88157\tP\tPPL\tAE\t\t06\t\t\t\t20165\t\t114\tAsia/Dubai\t2025-01-05',
 '292968\tAbu Dhabi\tAbu Dhabi\tA-pu-that-pi,AEbu Saby,AUH,Aboe Dhabi,Abou Dabi,Abu Dabi,Abu Dabis,Abu Daby,Abu Daibi,Abu Dhabi,Abu Dhabi Island and Internal Islands City,Abu Dhabi emiraat,Abu Zabi,Abu Zaby,Abu Zabye,Abu Zabyo,Abu Ḍabi,Abu Ḑabi,Abu-Dabi,Abu-Dabi khot,Abu-Dabio,Abu-Dzabi,Abú Dabí,Abú Daibí,Abú Zabí,Abû Daby,Abū Dabī,Abū Z̧aby,Abū Z̧abye,Abū Z̧abyo,Abū Z̧abī,Ampou Ntampi,Ebu Dabi,Ebu Dhabi,a bu zha bi,abu dhabi,abu-dabi,abudabi,abudhabi,abw zby,abwzby,aputapi,jzyrt abwzby wjzr dakhlyt akhry,xa bud abi,Â-pu-tha̍t-pí,Äbu Saby,Əbu-Dabi,Άμπου Ντάμπι,Αμπου Νταμπι,Αμπού Ντάμπι,Абу Даби,Абу-Даби,Абу-Даби хот,Абу-Дабі,Әбу-Даби,Աբու Դաբի,אבו דאבי,أبوظبي,ئەبووزەبی,ابو ظبى,ابوظبی,ابوظہبی,جزيرة أبوظبي وجزر داخلية اخرى,अबु धाबी,अबू धाबी,আবুধাবি,ਅਬੂ ਧਾਬੀ,ଆବୁଧାବି,அபுதாபி,ಅಬು ಧಾಬಿ,അബുദാബി,අබුඩාබි,อาบูดาบี,ཨ་པོའུ་དྷ་པེ།,အဘူဒါဘီမြို့,აბუ-დაბი,አቡ ዳቢ,アブダビ,阿布扎比,아부다비\t24.45118\t54.39696\tP\tPPLC\tAE\t\t01\t101\t\t\t1807000\t\t6\tAsia/Dubai\t2024-03-27',
 '292991\tAbū Hayl\tAbu Hayl\tAbu Hail,Hail,Hāil\t25.28413\t55.33153\tP\tPPLX\tAE\t\t03\t\t\t\t18043\t\t3\tAsia/Dubai\t2024-10-28',
 '385024\tAs Saţwah\tAs Satwah\tAl Satwa,As Satwah,As Saţwah,Satwa,alstwh,السطوه\t25.22192\t55.27459\tP\tPPLX\tAE\t\t03\t\t\t\t40997\t\t9\tAsia/Dubai\t2024-10-28',
 '414901\tAl Ḩamīdīyah\tAl Hamidiyah\tAl Hamidiyah,Al Ḩamīdīyah,alhmydyt,الحميدية\t25.40001\t55.52925\tP\tPPLX\tAE\t\t02\t\t\t\t27000\t\t15\tAsia/Dubai\t2024-04-03',
 '6691079\tAl Waheda\tAl Waheda\t\t25.29173\t55.33822\tP\tPPLX\tAE\t\t03\t\t\t\t21608\t\t-1\tAsia/Dubai\t2024-10-28',
 '6691091\tAl Karama\tAl Karama\t\t25.24004\t55.30106\tP\tPPLX\tAE\t\t03\t\t\t\t75560\t\t4\tAsia/Dubai\t2024-10-28',
 '6691096\tAl Wasl\tAl Wasl\t\t25.19881\t55.25565\tP\tPPLX\tAE\t\t03\t\t\t\t22153\t\t2\tAsia/Dubai\t2026-02-28',
 '6691113\tThe Palm Jumeirah\tThe Palm Jumeirah\tPalm Jumeirah,nkhlt aljmyrt,نخلة الجميرة\t25.11607\t55.13506\tP\tPPL\tAE\t\t03\t\t\t\t25500\t\t-9999\tAsia/Dubai\t2024-10-28',
 '7289825\tBur Dubai\tBur Dubai\tbr dby,بر دبي\t25.26038\t55.29891\tP\tPPL\tAE\t\t03\t\t\t\t18698\t\t11\tAsia/Dubai\t2024-04-03',
 '8057551\tKhalifah A City\tKhalifah A City\tKhalifah A City,Madinat Khalifah A,Madīnat Khalīfah A,mdynt khlyft a,mdynt khlyft a/ mtar abwzby aldwly,مدينة خليفة أ,مدينة خليفة أ/ مطار أبوظبي الدولي\t24.42588\t54.605\tP\tPPL\tAE\t\t01\t101\t12748080\t\t85374\t\t0\tAsia/Dubai\t2024-03-14',
 '8200824\tMirdif\tMirdif\tMirdif,mrdf,مردف\t25.22443\t55.41412\tP\tPPLX\tAE\t\t03\t\t\t\t60288\t\t24\tAsia/Dubai\t2024-10-28',
 "8201275\tHawr al ‘Anz\tHawr al 'Anz\tHawr al `Anz,Hawr al ‘Anz,Hor al Anz,هور العنز\t25.27744\t55.33675\tP\tPPLX\tAE\t\t03\t\t\t\t84661\t\t5\tAsia/Dubai\t2024-10-28",
 '8225407\tMankhūl\tMankhul\tAl Mankhool,Mankhool,Mankhul,Mankhūl,mnkhwl,منخول\t25.24612\t55.29222\tP\tPPLX\tAE\t\t03\t\t\t\t41244\t\t0\tAsia/Dubai\t2024-10-28',
 '8226485\tNāyf\tNayf\tNaif,Nayf,Nāyf,nayf,نايف\t25.27139\t55.30323\tP\tPPLX\tAE\t\t03\t\t\t\t53075\t\t9\tAsia/Dubai\t2024-10-28',
 '8226590\tAl Murar al Qadīm\tAl Murar al Qadim\tAl Murar,Al Murar al Qadeem,Al Murar al Qadim,Al Murar al Qadīm,almrr alqdym,المرر القديم\t25.27576\t55.30738\tP\tPPLX\tAE\t\t03\t\t\t\t19831\t\t8\tAsia/Dubai\t2024-10-28',
 '8469658\tAl Warqaa\tAl Warqaa\tAl Warqaa\t25.19272\t55.42013\tP\tPPLX\tAE\t\t03\t\t\t\t59111\t\t29\tAsia/Dubai\t2024-10-28',
 '8469668\tInternational City\tInternational City\tDubai International City,International City\t25.16383\t55.40987\tP\tPPLX\tAE\t\t03\t\t\t\t120000\t\t15\tAsia/Dubai\t2024-11-13',
 '8469788\tDubai Marina\tDubai Marina\tDubai Marina,Dubaj Marina,Dubaja Jakthaveno,Dubaï Marina,Marina de Dubai,Marina de Dubái,dby maryna,dobaimarina,dubai marina,mrsy dby,Дубай Марина,دبی مارینا,مرسى دبي,დუბაი მარინა,ドバイマリーナ\t25.08525\t55.14646\tP\tPPLX\tAE\t\t03\t\t\t\t120000\t\t-9\tAsia/Dubai\t2024-04-03',
 '8469811\tDubai Internet City\tDubai Internet City\tDubai Internet City\t25.09538\t55.16171\tP\tPPLX\tAE\t\t03\t\t\t\t24000\t\t-9\tAsia/Dubai\t2024-04-03',
 '8469819\tAl Safa\tAl Safa\tAl Safa\t25.17047\t55.23336\tP\tPPLX\tAE\t\t03\t\t\t\t15672\t\t0\tAsia/Dubai\t2024-10-28',
 '8475866\tAr Rumaylah\tAr Rumaylah\tAr Rumaylah,alrmylt,الرميلة\t25.40338\t55.4334\tP\tPPLX\tAE\t\t02\t\t\t\t86000\t\t2\tAsia/Dubai\t2024-04-03',
 '8475923\tAl Jurf\tAl Jurf\tAl Jurf,aljrf,الجرف\t25.41814\t55.50791\tP\tPPLX\tAE\t\t02\t\t\t\t18000\t\t6\tAsia/Dubai\t2024-04-03',
 '8476509\tAl Majaz\tAl Majaz\t\t25.32354\t55.38774\tP\tPPLX\tAE\t\t06\t\t\t\t116503\t\t10\tAsia/Dubai\t2024-10-28',
 '8541937\tDubai Festival City\tDubai Festival City\t\t25.22177\t55.35733\tP\tPPLX\tAE\t\t03\t\t\t\t77000\t\t4\tAsia/Dubai\t2024-04-03',
 '8541977\tDubai International Financial Centre\tDubai International Financial Centre\t\t25.2106\t55.27787\tP\tPPLX\tAE\t\t03\t\t\t\t36000\t\t7\tAsia/Dubai\t2024-04-03',
 '11048853\tDubai Investments Park\tDubai Investments Park\t\t25.00827\t55.15682\tP\tPPLX\tAE\t\t03\t\t\t\t160000\t0\t5\tAsia/Dubai\t2024-04-03',
 '11524601\tJebel Ali\tJebel Ali\tjbl ʿly,جبل علي\t25.00255\t55.10811\tP\tPPL\tAE\t\t03\t\t\t\t210000\t\t5\tAsia/Dubai\t2024-04-03',
 '12042052\tBani Yas City\tBani Yas City\tBani Yas,Bani Yas City,mdynt bny yas,مدينة بني ياس\t24.30978\t54.62944\tP\tPPL\tAE\t\t01\t101\t12748028\t\t80498\t\t14\tAsia/Dubai\t2024-03-14',
 '12042053\tMusaffah\tMusaffah\tMusaffa,Musaffah City,msfh,Мусаффа,مصفح\t24.35893\t54.48267\tP\tPPL\tAE\t\t01\t101\t12748041\t\t243341\t\t7\tAsia/Dubai\t2024-03-14',
 '12047416\tAl Shamkhah City\tAl Shamkhah City\tAl Shamkhah City,mdynt alshamkht,مدينة الشامخة\t24.39268\t54.70779\tP\tPPL\tAE\t\t01\t101\t12748001\t\t61710\t\t34\tAsia/Dubai\t2024-03-14',
 '12047417\tReef Al Fujairah City\tReef Al Fujairah City\tReef Al Fujairah City,ryf alfjyrt,ريف الفجيرة\t25.14479\t56.24764\tP\tPPL\tAE\t\t04\t\t\t\t82310\t\t129\tAsia/Dubai\t2019-05-29',
 "13118420\tAl Bada'a\tAl Bada'a\talbdʿ,البدع\t25.22462\t55.26888\tP\tPPLX\tAE\t\t03\t300\t333\t\t18816\t\t11\tAsia/Dubai\t2024-10-28",
 '13118421\tAl Muteena\tAl Muteena\tMuteena\t25.27375\t55.32265\tP\tPPLX\tAE\t\t03\t100\t123\t\t48739\t\t20\tAsia/Dubai\t2024-10-28',
 '13118422\tAl Mizhar First\tAl Mizhar First\tAl Mizhar 1\t25.24805\t55.44128\tP\tPPLX\tAE\t\t03\t200\t262\t\t17498\t\t24\tAsia/Dubai\t2024-10-28',
 '13118424\tDubai Silicon Oasis\tDubai Silicon Oasis\tSilicon Oasis\t25.11985\t55.38718\tP\tPPLX\tAE\t\t03\t600\t626\t\t90000\t\t11\tAsia/Dubai\t2024-10-28',
 '13118431\tAl Furjan\tAl Furjan\t\t25.02651\t55.14565\tP\tPPLX\tAE\t\t03\t500\t591\t\t26000\t\t16\tAsia/Dubai\t2024-10-28',
 '13118432\tBusiness Bay\tBusiness Bay\t\t25.18544\t55.26969\tP\tPPLX\tAE\t\t03\t300\t346\t\t191000\t\t16\tAsia/Dubai\t2024-10-28',
 '13118433\tAl Qusais 1\tAl Qusais 1\tAl Qusais First\t25.27925\t55.36995\tP\tPPLX\tAE\t\t03\t200\t232\t\t48378\t\t11\tAsia/Dubai\t2024-10-28',
 '13118437\tHalwan\tHalwan\t\t25.34586\t55.42165\tP\tPPL\tAE\t\t06\t\t\t\t19389\t\t16\tAsia/Dubai\t2024-10-28',
 '13118438\tAl Sajaah\tAl Sajaah\t\t25.31532\t55.63211\tP\tPPL\tAE\t\t06\t\t\t\t53079\t\t67\tAsia/Dubai\t2024-10-28',
 '13118439\tLahbab\tLahbab\tLehbab,lhbab,لهباب\t25.03763\t55.59135\tP\tPPL\tAE\t\t03\t700\t731\t\t53079\t\t125\tAsia/Dubai\t2024-10-28',
 '13118447\tMohammed Bin Zayed City\tMohammed Bin Zayed City\tMohammed Bin Zayed\t24.34794\t54.55368\tP\tPPL\tAE\t\t01\t101\t12747966\t\t85000\t\t3\tAsia/Dubai\t2024-10-28',
 '1120985\tZaranj\tZaranj\tSarandsch,ZAJ,Zaranas,Zarandj,Zarandz,Zarandzas,Zarandzh,Zarandż,Zarandžas,Zarang,Zarani,Zaranj,Zaranzh,Zaranĝ,Zerenc,Zhazang,Zərənc,jaranja,zaraniji,zaranja,zaranji,zha lan ji,zrnj,Зарандж,Заранж,Зарани,Заранҷ,زرنج,ज़रंज,জারান্জ,ਜ਼ਰਾਂਜ,ዛራንጅ,ザラーンジ,扎兰季\t30.95962\t61.86037\tP\tPPLA\tAF\t\t19\t2201\t\t\t49851\t\t489\tAsia/Kabul\t2026-04-13',
 '1121381\tBāzār-e Yakāwlang\tBazar-e Yakawlang\tBazar-e Yakavlang,Bazar-e Yakawlang,Bazar-e Yekawlang,Bazare Yakawlang,Bazari-Yakavlang,Bāzār-e Yakāvlang,Bāzār-e Yakāwlang,Bāzār-e Yekāwlang,Bāzāṟe Yakāwlang,Yakaulang,Yakavlang,Yakawlang,Yakāvlang,Yakāwlang,bazar ykawlng,بازار يکاولنگ\t34.73525\t66.97379\tP\tPPLW\tAF\t\t05\t2804\t\t\t65000\t\t2585\tAsia/Kabul\t2020-01-02',
 '1123004\tTaloqan\tTaloqan\tKhanabad,TQN,Taikhan,Taleqan,Talikan,Talikhan,Talikˌon,Taliqan,Talkan,Talogan,Talokan,Talokˌan,Taloqan,Talugan,Talukan,Talukanas,Taluqan,Tologan,Tâloqân,Tāleqān,Tāloqān,Tāluqān,Tālīqān,ta lu kan,talokam,talokana,talokuvan,taloqana,taloqani,talqan,tarokan,Таликан,Талиқон,Талокан,Талоқан,Талукан,تالقان,तालोक़ान,तालोकां,তালোকান,ਤਾਲੋਕਾਨ,தலோகுவான்,თალიკანი,ታሎቃን,タロカン,塔卢坎\t36.73605\t69.53451\tP\tPPLA\tAF\t\t26\t1201\t\t\t64256\t\t801\tAsia/Kabul\t2026-04-13',
 '1125155\tShīnḏanḏ\tShindand\tAsfazar,Asfazār,OAH,Sabzavar,Sabzavār,Sabzawar,Sabzevar,Sabzevār,Shindan,Shindand,Shyndan,Shīndand,Shīnḏanḏ,Sindand,shindando,shinidanidi,shndnd,shyndnd,sidanda,sindanda,Šīndand,Шиндан,Шинданд,Шындан,شندند,شيندند,شیندند,شینډنډ,शिंदंद,শিন্দান্দ,ਸ਼ਿੰਦਾਂਦ,ሽንዳንድ,シンダンド\t33.30294\t62.1474\tP\tPPLA2\tAF\t\t11\t2014\t\t\t29264\t\t1071\tAsia/Kabul\t2026-04-16',
 '1125444\tShibirghān\tShibirghan\tChibirchan,Markaz-e Wilayat-e Shibirghan,Markaz-e Wilāyat-e Shibirghan,Schibirgan,Seberghan,Sebeṟghān,Shahr-e Sheberghan,Shahr-e Sheberghān,Shayurgan,Shebergan,Sheberghan,Sheberghān,Sheberkhan,Shefrogan,Shibarghan,Shibarghān,Shibergan,Shibirgan,Shibirghan,Shibirghān,Shibirgon,Shibirgán,Shoburgon,Sibircan,Sibircən,mrkz wlayt shbrghan,shbrghan,shbrghn,shibirigani,shibirugan,sibiraghana,Şibircân,Şibircən,Шеберган,Шибирган,Шибирған,Шибирғон,شبرغان,شبرغن,مرکز ولايت شبرغان,शिबिरघान,শিবিরঘান,ਸ਼ਿਬਿਰਘਾਨ,ሽብርጋን,シビルガン\t36.66757\t65.7529\tP\tPPLA\tAF\t\t31\t1701\t\t\t55641\t\t360\tAsia/Kabul\t2026-04-13',
 '1125896\tShahrak\tShahrak\tBati Dara,Kala Shaharak,Kala Shahrak,Kala Shahārak,Markaz-e Shahrak,Qal`eh Shaharak,Qal`eh-ye Bati Darrah,Qala Bati Dara,Qala Batī Dara,Qala Shaharak,Qala Shahārak,Qala Sharak,Qal‘eh Shahārak,Qal‘eh-ye Bati Darrah,Sahrak,Shahrag,Shahrak,Shakhrak,Sharak,Shāhrag,Shāhrak,Wala Shahrak,saharaka,shafuraku,shahhiraki,shhrk,shہrk,Şahrak,Šahrak,Шахрак,شهرك,شهرک,شہرک,शहरक,শাহরাক,ਸ਼ਾਹਰਾਕ,ሻሕራክ,シャフラク\t34.10737\t64.3052\tP\tPPLA2\tAF\t\t09\t2702\t\t\t15967\t\t2357\tAsia/Kabul\t2026-04-16',
 "1127110\tSar-e Pul\tSar-e Pul\tSar-e Pol,Sar-e Poul,Sar-e Pul,Sar-i-Pul,Sari Pul,Sari-Pul,Sari-Pul',Saripo'l,sara-e pula,sara-i pula,sarepuru,sari-yu ፑል,sr pl,srpl,Сари Пул,Сари-Пул,Сари-Пуль,سر پل,سرپل,सार-ए पुल,সার-ই পুল,ਸਾਰ-ਏ ਪੁਲ,ሳር-ዩ ፑል,サレプル\t36.21544\t65.93249\tP\tPPLA\tAF\t\t33\t3101\t\t\t52121\t657\t636\tAsia/Kabul\t2026-04-13",
 '1127628\tSang-e Chārak\tSang-e Charak\tSang-e Charak,Sang-e Chārak,Sangcharak,sngchark,Сангчарак,سنگچارک\t35.84972\t66.43694\tP\tPPL\tAF\t\t33\t3102\t\t\t15377\t\t1483\tAsia/Kabul\t2026-05-02',
 "1127768\tAībak\tAibak\tAibak,Ajbak,Ajbakˌ,Aybak,Aïbak,Aībak,Eybak,Haibak,Samagan,Samangan,Samangān,a'ibaka,aibaka,aibaku,ay bk,aybk,smngan,Āybak,ʿeyibaki,Айбак,Айбақ,آي بك,آی بک,آیبک,ایبک,سمنگان,ऐबक,আইবক,ਐਬਕ,አይባክ,アイバク\t36.26468\t68.01551\tP\tPPLA\tAF\t\t32\t1501\t\t\t47823\t\t969\tAsia/Kabul\t2026-05-02",
 '1128265\tRustāq\tRustaq\tRostaq,Rostāq,Rustak,Rustaq,Rustokˌ,Rustāq,rstaq,rusataka,rusitaqi,rustaka,rusutaku,rwstaq,Рустак,Рустоқ,رستاق,روستاق,रुस्तक,রুস্তাক,ਰੁਸਤਾਕ,ሩስታቅ,Ṟustāq,ルスタク\t37.12604\t69.83045\tP\tPPLA2\tAF\t\t26\t1208\t\t\t25636\t\t1314\tAsia/Kabul\t2026-04-16',
 '1129516\tQarqīn\tQarqin\tKarkin,Karkin Bazar,Karkˌyn,Kkhanika,Kˌarkˌin,Kˌarkˌyn,Qarkin,Qarqin,Qarqīn,Qarqın,Quarkin,karakina,karukin,qariqini,qrqyn,Каркин,Карқын,Кханика,Қарқин,Қарқын,قرقین,कारकिन,কারকিন,ਕਾਰਕਿਨ,ቃርቅን,カルキン\t37.41853\t66.04358\tP\tPPLA2\tAF\t\t31\t1705\t\t\t15018\t\t263\tAsia/Kabul\t2026-04-16',

In [15]:
import csv

def parse_geonames(filepath):
    cleaned = []

    with open(filepath, encoding="utf-8") as f:
        reader = csv.reader(f, delimiter="\t")

        for row in reader:
            try:
                name = row[1].strip().lower()
                lat = float(row[4])
                lon = float(row[5])
                feature_code = row[7]
                population = int(row[14]) if row[14] else 0

                # filter only useful place types
                if not feature_code.startswith("PPL") and not feature_code.startswith("ADM"):
                    continue

                cleaned.append({
                    "name": name,
                    "lat": lat,
                    "lon": lon,
                    "feature_code": feature_code,
                    "population": population
                })

            except Exception:
                continue

    return cleaned

cleaned_data = parse_geonames(r"C:\Users\kuchbhe\Desktop\Travelara-ai\backend\tests\pipeline_test\data\cities15000\cities15000.txt")

cleaned_df = pd.DataFrame(cleaned_data)
cleaned_df.head()

                 name       lat       lon feature_code  population
0        les escaldes  42.50729   1.53414         PPLA       15853
1    andorra la vella  42.50779   1.52109         PPLC       20430
2             warīsān  25.16744  55.40708          PPL      108759
3          umm suqaym  25.15491  55.21015         PPLX       16459
4  umm al quwain city  25.56473  55.55517         PPLA       59098

In [23]:
cleaned_all = parse_geonames(r"C:\Users\kuchbhe\Desktop\Travelara-ai\backend\tests\pipeline_test\data\allCountries\allCountries.txt")
cleaned_all_df = pd.DataFrame(cleaned_all)
cleaned_all_df.head()

                 name       lat      lon feature_code  population
0           xixerella  42.55327  1.48736          PPL           0
1                vila  42.53176  1.56654          PPL        1418
2  tossalet i vinyals  42.48597  1.48910         PPLL           0
3              sornàs  42.56461  1.52757          PPL         251
4              soldeu  42.57688  1.66769          PPL         602

In [26]:
india_latlon = parse_geonames(r"C:\Users\kuchbhe\Desktop\Travelara-ai\backend\tests\pipeline_test\data\IN\IN.txt")
india_latlon_df = pd.DataFrame(india_latlon)
india_latlon_df.head()

             name       lat       lon feature_code  population
0         tithwāl  34.39351  73.77416          PPL           0
1          thruti  33.52682  74.15939          PPL           0
2           thang  34.92740  76.79336          PPL        1622
3           pūnch  33.77033  74.09254          PPL       28197
4  mahmūd khāneke  30.66711  74.21704          PPL           0

In [32]:
india_latlon_df[india_latlon_df.name == 'new delhi'.lower()]

            name       lat       lon feature_code  population
6861   new delhi  28.62137  77.21480         PPLC      317797
39906  new delhi  28.61770  77.20685         ADM2      142004

In [ ]:
cleaned_df[cleaned_df.name == 'Himachal Pradesh'.lower()]

Empty DataFrame
Columns: [name, lat, lon, feature_code, population]
Index: []

In [ ]:
import pandas as py
from dotenv import load_dotenv
import os

import requests
import time
import random
import serpapi
from pydantic import BaseModel, Field

load_dotenv()

SERP_API_KEY = os.getenv("SERP_API_KEY")

if not SERP_API_KEY:
    raise ValueError("SERP_API_KEY not found in environment variables.")

In [ ]:
from pydantic import BaseModel
from enum import Enum
from typing import List

# search i/p: engine, q (can be any search query), ll(lat, lon, zoom)
# NLU/NLP o/p: source, destination, days, budget, preferences, itinerary structure (should match with q/free flowing q based on assumption search engine can handle the query and return the relevant results), ...


# also need to calculate time taken / travel distance for within day sequential pairs using haversine and later on, use OSRM API to calculate the travel time/distance based on mode of transport (car, walk, public transport, etc.)

In [5]:
client = serpapi.Client(api_key=SERP_API_KEY)

results = client.search({
    "engine": "google_maps",
    "q": "tourist attractions",
    "ll": "@28.6139, 77.2090,14z"
})

results

{
    "search_metadata": {
        "id": "69f86edacfa230cef21bf06f",
        "status": "Success",
        "json_endpoint": "https://serpapi.com/searches/Wk9L_LxWe_Zyj-v4E91J4g/69f86edacfa230cef21bf06f.json",
        "created_at": "2026-05-04 10:03:06 UTC",
        "processed_at": "2026-05-04 10:03:06 UTC",
        "google_maps_url": "https://www.google.com/maps/search/tourist+attractions/@28.6139,77.2090,14z/?hl=en",
        "raw_html_file": "https://serpapi.com/searches/Wk9L_LxWe_Zyj-v4E91J4g/69f86edacfa230cef21bf06f.html",
        "prettify_html_file": "https://serpapi.com/searches/Wk9L_LxWe_Zyj-v4E91J4g/69f86edacfa230cef21bf06f.prettify",
        "total_time_taken": 0.62
    },
    "search_parameters": {
        "engine": "google_maps",
        "type": "search",
        "q": "tourist attractions",
        "ll": "@28.6139, 77.2090,14z",
        "google_domain": "google.com",
        "hl": "en"
    },
    "search_information": {
        "local_results_state": "Results for exact spelling",
        "query_displayed": "tourist attractions"
    },
    "local_results": [
        {
            "position": 1,
            "title": "Shish Gumbad",
            "place_id": "ChIJxZt5n-3iDDkRAruWCglWcYM",
            "data_id": "0x390ce2ed9f799bc5:0x837156090a96bb02",
            "data_cid": "9471446088169208578",
            "reviews_link": "https://serpapi.com/search.json?data_id=0x390ce2ed9f799bc5%3A0x837156090a96bb02&engine=google_maps_reviews&hl=en",
            "photos_link": "https://serpapi.com/search.json?data_id=0x390ce2ed9f799bc5%3A0x837156090a96bb02&engine=google_maps_photos&hl=en",
            "gps_coordinates": {
                "latitude": 28.593818499999998,
                "longitude": 77.2202047
            },
            "place_id_search": "https://serpapi.com/search.json?engine=google_maps&google_domain=google.com&hl=en&place_id=ChIJxZt5n-3iDDkRAruWCglWcYM",
            "provider_id": "/g/122fjcf0",
            "rating": 4.4,
            "reviews": 376,
            "unclaimed_listing": true,
            "type": "Tourist attraction",
            "types": [
                "Tourist attraction"
            ],
            "type_id": "tourist_attraction",
            "type_ids": [
                "tourist_attraction"
            ],
            "address": "H6VC+G3G, New, Lodhi Gardens, Lodhi Estate, New Delhi, Delhi 110003, India",
            "open_state": "Open \u00b7 Closes 8\u202fPM",
            "hours": "Open \u00b7 Closes 8\u202fPM",
            "operating_hours": {
                "monday": "7\u202fAM\u20138\u202fPM",
                "tuesday": "7\u202fAM\u20138\u202fPM",
                "wednesday": "7\u202fAM\u20138\u202fPM",
                "thursday": "7\u202fAM\u20138\u202fPM",
                "friday": "7\u202fAM\u20138\u202fPM",
                "saturday": "7\u202fAM\u20138\u202fPM",
                "sunday": "7\u202fAM\u20138\u202fPM"
            },
            "phone": "+91 11 2336 5358",
            "description": "Historic stone tomb with ornate features. Landmark, dome-shaped tomb constructed between 1489 & 1517 with intricate stone carvings.",
            "extensions": [
                {
                    "accessibility": [
                        "Wheelchair accessible parking lot"
                    ]
                },
                {
                    "amenities": [
                        "Restroom"
                    ]
                },
                {
                    "children": [
                        "Good for kids"
                    ]
                }
            ],
            "unsupported_extensions": [
                {
                    "accessibility": [
                        "Wheelchair accessible entrance"
                    ]
                }
            ],
            "user_review": "\"The sunset as it falls behind the gumbad in the west is so mesmerizing.\"",
            "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFL-vaF33PiD6cgc3KTgepw0nMMkuZ11WtFUNOW7BF9vD-h7cfnTywptIYVFRuvNlsAYqPKpKsMtIBdvjiT3Lz3LpoHiuSGu2tHf1JW7iwgbvV1G89Y7R4OvPiXmPnKO_fGtzsC0w=w1000-h1000-c-n",
            "serpapi_thumbnail": "https://serpapi.com/images/url/_wrCXHicHcTdTsMgGADQJ2IFMdaZeNG50M3-4VZX641RbCmuA5QPiHtDH8G3MfFcnN-fCcC6mySZJ7qQxsh58G74EkbDoGEhzCmR1iHhkEsyXj8cM1ai8Moo5Wp9JaSgRSsHG7GuqqN_JqQD9lg3Xbpiy7BGUypG3X5HC9v-wHY-1LPL-k9e2MJVsF29hw_V0vJMS2s2yu9zfwGbkdx3qYryLRxIfr3s091lE7h6OnFdNC9jDmd3h-NtJBhjNP0vkP4D4aRFrg"
        },
        {
            "position": 2,
            "title": "Baba Banda Singh Bahadur Statue",
            "place_id": "ChIJyXpGpiz9DDkRVmEP8X1Nt9k",
            "data_id": "0x390cfd2ca6467ac9:0xd9b74d7df10f6156",
            "data_cid": "15688093030278979926",
            "reviews_link": "https://serpapi.com/search.json?data_id=0x390cfd2ca6467ac9%3A0xd9b74d7df10f6156&engine=google_maps_reviews&hl=en",
            "photos_link": "https://serpapi.com/search.json?data_id=0x390cfd2ca6467ac9%3A0xd9b74d7df10f6156&engine=google_maps_photos&hl=en",
            "gps_coordinates": {
                "latitude": 28.625867,
                "longitude": 77.2345948
            },
            "place_id_search": "https://serpapi.com/search.json?engine=google_maps&google_domain=google.com&hl=en&place_id=ChIJyXpGpiz9DDkRVmEP8X1Nt9k",
            "provider_id": "/g/11c6chw9kl",
            "rating": 4.6,
            "reviews": 44,
            "unclaimed_listing": true,
            "type": "Tourist attraction",
            "types": [
                "Tourist attraction"
            ],
            "type_id": "tourist_attraction",
            "type_ids": [
                "tourist_attraction"
            ],
            "address": "Metro Station Mandi House, Mandi House, New Delhi, Delhi 110001, India",
            "open_state": "Open 24 hours",
            "hours": "Open 24 hours",
            "operating_hours": {
                "monday": "Open 24 hours",
                "tuesday": "Open 24 hours",
                "wednesday": "Open 24 hours",
                "thursday": "Open 24 hours",
                "friday": "Open 24 hours",
                "saturday": "Open 24 hours",
                "sunday": "Open 24 hours"
            },
            "phone": "+91 98718 87064",
            "extensions": [
                {
                    "children": [
                        "Good for kids"
                    ]
                }
            ],
            "user_review": "\"The statue itself is a masterpiece of craftsmanship.\"",
            "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGFrKCztImVBtRQwd1ur3MrXXHL35_RzAd3LYHn-vY-ARE4PsrCUVVt2ZIl2phxYpgRwJ-zgxuj_vTko44T-ppgJfb9iEWf0qJQqMERlXBVUBpspBCe5mwn725e3IwE2Vj7DJSbQA=w1000-h1000-c-n",
            "serpapi_thumbnail": "https://serpapi.com/images/url/zoDn5nicHcRdDoIgAADgE5EmulZbD2hW2s-SirSXtoywUiDAaN6wI3Sbtr6H7_upjJF65Dh1BXtMCFbTVlNVCm4oN71SNA6TGpQaaAdt1tkDzaZqEXUmaUhocGYv_VbBlcrz-RIGJ9yhC1wWcw5eBUA49jdaRXtCjHdMak9W70IybFPQsXd7P712D-H7OyAlS6_n4S0-XN1nmj1XMa7zkOxDqWUY0aCxfOAFFCY29sh9MEm35wyNbd91XVD9LwH_AQE-RSo"
        },
        {
            "position": 3,
            "title": "Yamuna River View Point No.-3",
            "place_id": "ChIJlfXXDp_jDDkRz7_xyprF9YI",
            "data_id": "0x390ce39f0ed7f595:0x82f5c59acaf1bfcf",
            "data_cid": "9436665862845218767",
            "reviews_link": "https://serpapi.com/search.json?data_id=0x390ce39f0ed7f595%3A0x82f5c59acaf1bfcf&engine=google_maps_reviews&hl=en",
            "photos_link": "https://serpapi.com/search.json?data_id=0x390ce39f0ed7f595%3A0x82f5c59acaf1bfcf&engine=google_maps_photos&hl=en",
            "gps_coordinates": {
                "latitude": 28.6018248,
                "longitude": 77.2662623
            },
            "place_id_search": "https://serpapi.com/search.json?engine=google_maps&google_domain=google.com&hl=en&place_id=ChIJlfXXDp_jDDkRz7_xyprF9YI",
            "provider_id": "/g/11fl8_t616",
            "rating": 4,
            "reviews": 1546,
            "unclaimed_listing": true,
            "type": "Tourist attraction",
            "types": [
                "Tourist attraction"
            ],
            "type_id": "tourist_attraction",
            "type_ids": [
                "tourist_attraction"
            ],
            "address": "J728+PGC, Yamuna Bridge, East End down, Delhi - Meerut Expy, Delhi 110092, India",
            "open_state": "Open 24 hours",
            "hours": "Open 24 hours",
            "operating_hours": {
                "monday": "Open 24 hours",
                "tuesday": "Open 24 hours",
                "wednesday": "Open 24 hours",
                "thursday": "Open 24 hours",
                "friday": "Open 24 hours",
                "saturday": "Open 24 hours",
                "sunday": "Open 24 hours"
            },
            "extensions": [
                {
                    "service_options": [
                        "Onsite services"
                    ]
                },
                {
                    "amenities": [
                        "Restroom"
                    ]
                },
                {
                    "payments": [
                        "NFC mobile payments"
                    ]
                },
                {
                    "children": [
                        "Good for kids"
                    ]
                },
                {
                    "parking": [
                        "Free parking lot",
                        "Free street parking",
                        "Paid parking lot"
                    ]
                }
            ],
            "service_options": {
                "onsite_services": true
            },
            "user_review": "\"Feelling amazed post see the View of sunset.\"",
            "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGp0EX3buSSidH1dP4XpkaSPu_hzRqcvARVDV-8GLhcanHdgUyS_GjvVZg-B9do2-tLqe6lut0DPXLU6t8eQGSdoZnoBKDwPmeH9ZngcuyyXgbydADU9YcmidA0jZ5ryEyIBkkB=w1000-h1000-c-n",
            "serpapi_thumbnail": "https://serpapi.com/images/url/5N-tQnicHcRdDoIgAADgE5H0u2zrAafTlmsU05kvroCBqWABNbpgZ-g2bX0P3_cjrR3NJgh6OZ8IrUXPneEPqpXlyk6oHgIxGkANMAHCh2OH0hEm1fzqCGlZNmV4UY3dhWDXyPfpTp_oVMYlWKe5pBeVMVF40qS3Z1kLEIVMz4DN73zVOwtjXOXFyq75MSVM10pH-_iFB56FtRLUeV-Jq2coLsIzHVqG4K1ePnzid1HXRdvXFEII5H8K1A-h4EXI"
        },
        {
            "position": 4,
            "title": "Humayun\u2019s Tomb",
            "place_id": "ChIJpwtG6BzjDDkRDajfOy268bk",
            "data_id": "0x390ce31ce8460ba7:0xb9f1ba2d3bdfa80d",
            "data_cid": "13398695069844744205",
            "reviews_link": "https://serpapi.com/search.json?data_id=0x390ce31ce8460ba7%3A0xb9f1ba2d3bdfa80d&engine=google_maps_reviews&hl=en",
            "photos_link": "https://serpapi.com/search.json?data_id=0x390ce31ce8460ba7%3A0xb9f1ba2d3bdfa80d&engine=google_maps_photos&hl=en",
            "gps_coordinates": {
                "latitude": 28.5932848,
                "longitude": 77.2507492
            },
            "place_id_search": "https://serpapi.com/search.json?engine=google_maps&google_domain=google.com&hl=en&place_id=ChIJpwtG6BzjDDkRDajfOy268bk",
            "provider_id": "/m/04w9c2",
            "rating": 4.5,
            "reviews": 50323,
            "type": "Tourist attraction",
            "types": [
                "Tourist attraction",
                "Historical landmark"
            ],
            "type_id": "tourist_attraction",
            "type_ids": [
                "tourist_attraction",
                "historical_landmark"
            ],
            "address": "Hazrat Nizamuddin Aulia Dargah, Mathura Rd, Nizamuddin, Nizamuddin East, New Delhi, Delhi 110013, India",
            "open_state": "Open now",
            "website": "https://www.delhitourism.gov.in/tourist_place/humayun_tomb.html",
            "description": "Palatial 16th-century tomb of Humayun. Opulent red-sandstone tomb of Mughal Emperor Humayun, built in 1572 & surrounded by formal gardens.",
            "extensions": [
                {
                    "service_options": [
                        "Onsite services"
                    ]
                },
                {
                    "accessibility": [
                        "Wheelchair accessible parking lot",
                        "Wheelchair accessible restroom",
                        "Wheelchair accessible seating"
                    ]
                },
                {
                    "payments": [
                        "Google Pay"
                    ]
                },
                {
                    "children": [
                        "Good for kids"
                    ]
                },
                {
                    "parking": [
                        "Free parking lot",
                        "Free street parking",
                        "Paid parking lot",
                        "Paid street parking"
                    ]
                }
            ],
            "unsupported_extensions": [
                {
                    "accessibility": [
                        "Wheelchair accessible entrance"
                    ]
                }
            ],
            "service_options": {
                "onsite_services": true
            },
            "user_review": "\"The architecture is stunning and the gardens are well-maintained.\"",
            "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGWSuJ1TN8cdnvmtWezDCZhXBGFSXYUXjkb8avNxjLr0-SSVdp9Ccm-sV_5RA_I4XfsLZXfLAKoXvcZtC_O7UVdis4QzjX9lFYX50CtJ6v69eUiiUK1v-dr7p9HgqILob_NdG1u=w1000-h1000-c-n",
            "serpapi_thumbnail": "https://serpapi.com/images/url/2c4DF3icHcRJDoIwAADAF1VKFBATD4gBF4ILAoULkbayCBRpqcYP-gZ_Y-Ic5vsphej5QlGacjopGCsaOnI6YNYJ2okJZq1S9BxgDrhiHf3T3XLjYNypF3-OSSdbEdP32k5LtHKdACUhqu_5_Cr9V-0NEARBRHrTxi3gUaadrWw7QzfupejmWXuGJE6FnR2MMCIVn53eNTIbJ0EatMVOl7pJw6oK96oEZDB6c1M8th7LM5-46rh8qhBCUP7HoPsBephErA"
        },
        {
            "position": 5,
            "title": "Sunset Point - Akshardham",
            "place_id": "ChIJ65X5ZU_jDDkRKSTq2hYlATw",
            "data_id": "0x390ce34f65f995eb:0x3c012516daea2429",
            "data_cid": "4323777897344672809",
            "reviews_link": "https://serpapi.com/search.json?data_id=0x390ce34f65f995eb%3A0x3c012516daea2429&engine=google_maps_reviews&hl=en",
            "photos_link": "https://serpapi.com/search.json?data_id=0x390ce34f65f995eb%3A0x3c012516daea2429&engine=google_maps_photos&hl=en",
            "gps_coordinates": {
                "latitude": 28.6178481,
                "longitude": 77.279147
            },
            "place_id_search": "https://serpapi.com/search.json?engine=google_maps&google_domain=google.com&hl=en&place_id=ChIJ65X5ZU_jDDkRKSTq2hYlATw",
            "provider_id": "/g/11fjgrhcvq",
            "rating": 4.7,
            "reviews": 32,
            "unclaimed_listing": true,
            "type": "Tourist attraction",
            "types": [
                "Tourist attraction"
            ],
            "type_id": "tourist_attraction",
            "type_ids": [
                "tourist_attraction"
            ],
            "address": "J79H+4MJ, Pandav Nagar, New Delhi, Delhi, 110092, India",
            "phone": "+91 11 2464 7005",
            "extensions": [
                {
                    "accessibility": [
                        "Wheelchair accessible entrance",
                        "Wheelchair accessible parking lot"
                    ]
                },
                {
                    "children": [
                        "Good for kids"
                    ]
                }
            ],
            "user_review": "\"It is a place where you heal your anxiety and tiredness.\"",
            "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFqq0qYSv5dcJTxF_dP1uyWABpMM0qlkMyqO9RKBuk21DUKb2mWoWnV_nGgR5l5ahnudrFnAA8UYcl_wogrUmSJZUVTysi2k7AFAKg3dHZkuhJhx28XNLwP-Omy3r3BnxLaTXoIYw=w1000-h1000-c-n",
            "serpapi_thumbnail": "https://serpapi.com/images/url/gB07U3icHcTdzoIgAADQJyJR5_rZusA1K82y0sxuXKGDBoKIpD5ij9DbfNt3Ls7vS_u-1SvL4tSdESkJr42uOyxFX4t-hmVjkVYDrIG2UHI8MxQoBVVx_XgVDtMxKKvENlOO_DaOoeIsntRpeYl8wxx7k0Uvp8llLm6l2JKLx70nFabqAoHQIiswLwdJuqy5ho_slk767bA5ClBE3Gr3YIaGdHQW9-NhSMCpmdzO9cV4eKZ3uS-G9WBDCAH9HwPxB08oRnY"
        },
        {
            "position": 6,
            "title": "Dilip Delhi Tuk Tuk Tours",
            "place_id": "ChIJPRKpga39DDkRahX34kDAabk",
            "data_id": "0x390cfdad81a9123d:0xb969c040e2f7156a",
            "data_cid": "13360421154489570666",
            "reviews_link": "https://serpapi.com/search.json?data_id=0x390cfdad81a9123d%3A0xb969c040e2f7156a&engine=google_maps_reviews&hl=en",
            "photos_link": "https://serpapi.com/search.json?data_id=0x390cfdad81a9123d%3A0xb969c040e2f7156a&engine=google_maps_photos&hl=en",
            "gps_coordinates": {
                "latitude": 28.6250017,
                "longitude": 77.2058893
            },
            "place_id_search": "https://serpapi.com/search.json?engine=google_maps&google_domain=google.com&hl=en&place_id=ChIJPRKpga39DDkRahX34kDAabk",
            "provider_id": "/g/11vspg30f4",
            "rating": 5,
            "reviews": 43,
            "type": "Tourist attraction",
            "types": [
                "Tourist attraction"
            ],
            "type_id": "tourist_attraction",
            "type_ids": [
                "tourist_attraction"
            ],
            "address": "4, Dr Bishambar Das Marg, Baba Kharak Singh Marg Area, New Delhi, Delhi, 110001, India",
            "open_state": "Open 24 hours",
            "hours": "Open 24 hours",
            "operating_hours": {
                "monday": "Open 24 hours",
                "tuesday": "Open 24 hours",
                "wednesday": "Open 24 hours",
                "thursday": "Open 24 hours",
                "friday": "Open 24 hours",
                "saturday": "Open 24 hours",
                "sunday": "Open 24 hours"
            },
            "phone": "+91 85277 60359",
            "website": "https://www.facebook.com/profile.php?id=61569734016819&mibextid=ZbWKwL",
            "extensions": [
                {
                    "children": [
                        "Good for kids"
                    ]
                }
            ],
            "user_review": "\"Nice tour with lots of fun \ud83d\udc4c\ud83d\udc4d\"",
            "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFmeHeDxUojusuq61jTFWYEHvmDcLICD76r_xZMbpToC-j9EC9nOkANMfkU3-7gfi0ezCVZYmpiyTaq8phj4Jd1_RxMkAeL4zdIVcy6Q5mVa3kHVuT00qxDjPLrG0Vs2b3B_YHriwskWG4F=w1000-h1000-c-n",
            "serpapi_thumbnail": "https://serpapi.com/images/url/AESj83icHcRJDoIwAADAF1WKIC6JBwQRDbgFa-BCsFagtbRQUPSTnv2NiXOY76doW6lmmnYvjEEuRH4nnSINFlVLqnaABddyqQBWQGn2fntgtseJT9z-JGinutrSaeSd46X_4C4O1o47tpq0T8KLjIQD6HTpTKsds7fhjZ0MMM5vJSRvByUxl-UryuqJLKi5uerpsQ-ZTQLzfV0j_LIOI44yg_moiyCse5fug2YFkRpejEUa-035VOy8Mr35U4cQguI_BtUP0DRHmg"
        },
        {
            "position": 7,
            "title": "Safdarjung Tomb, Delhi",
            "place_id": "ChIJVcXN6ZHiDDkR7DeT_RtRCc0",
            "data_id": "0x390ce291e9cdc555:0xcd09511bfd9337ec",
            "data_cid": "14774429233225873388",
            "reviews_link": "https://serpapi.com/search.json?data_id=0x390ce291e9cdc555%3A0xcd09511bfd9337ec&engine=google_maps_reviews&hl=en",
            "photos_link": "https://serpapi.com/search.json?data_id=0x390ce291e9cdc555%3A0xcd09511bfd9337ec&engine=google_maps_photos&hl=en",
            "gps_coordinates": {
                "latitude": 28.5894156,
                "longitude": 77.21062189999999
            },
            "place_id_search": "https://serpapi.com/search.json?engine=google_maps&google_domain=google.com&hl=en&place_id=ChIJVcXN6ZHiDDkR7DeT_RtRCc0",
            "provider_id": "/m/02q8l_h",
            "rating": 4.4,
            "reviews": 16066,

In [7]:
client = serpapi.Client(api_key=SERP_API_KEY)

results = client.search({
    "engine": "google_maps",
    "q": "cafes",
    "ll": "@28.6139, 77.2090,14z"
})

results

{
    "search_metadata": {
        "id": "69f8a285b13aa72d339853c3",
        "status": "Success",
        "json_endpoint": "https://serpapi.com/searches/D_BfKuJAXR8P2WRUNCNtoA/69f8a285b13aa72d339853c3.json",
        "created_at": "2026-05-04 13:43:33 UTC",
        "processed_at": "2026-05-04 13:43:33 UTC",
        "google_maps_url": "https://www.google.com/maps/search/cafes/@28.6139,77.2090,14z/?hl=en",
        "raw_html_file": "https://serpapi.com/searches/D_BfKuJAXR8P2WRUNCNtoA/69f8a285b13aa72d339853c3.html",
        "prettify_html_file": "https://serpapi.com/searches/D_BfKuJAXR8P2WRUNCNtoA/69f8a285b13aa72d339853c3.prettify",
        "total_time_taken": 1.03
    },
    "search_parameters": {
        "engine": "google_maps",
        "type": "search",
        "q": "cafes",
        "ll": "@28.6139, 77.2090,14z",
        "google_domain": "google.com",
        "hl": "en"
    },
    "search_information": {
        "local_results_state": "Results for exact spelling",
        "query_displayed": "cafes"
    },
    "local_results": [
        {
            "position": 1,
            "title": "Triveni Terrace Cafe",
            "place_id": "ChIJgYWp8Cz9DDkRHGRazZ5BlZg",
            "data_id": "0x390cfd2cf0a98581:0x9895419ecd5a641c",
            "data_cid": "10994766215600825372",
            "reviews_link": "https://serpapi.com/search.json?data_id=0x390cfd2cf0a98581%3A0x9895419ecd5a641c&engine=google_maps_reviews&hl=en",
            "photos_link": "https://serpapi.com/search.json?data_id=0x390cfd2cf0a98581%3A0x9895419ecd5a641c&engine=google_maps_photos&hl=en",
            "gps_coordinates": {
                "latitude": 28.6272268,
                "longitude": 77.2324197
            },
            "place_id_search": "https://serpapi.com/search.json?engine=google_maps&google_domain=google.com&hl=en&place_id=ChIJgYWp8Cz9DDkRHGRazZ5BlZg",
            "provider_id": "/g/11bcf2spp7",
            "rating": 4.4,
            "reviews": 6539,
            "price": "\u20b9400\u2013600",
            "extracted_price": 400,
            "type": "Cafe",
            "types": [
                "Cafe",
                "Coffee shop",
                "North Indian restaurant",
                "Restaurant"
            ],
            "type_id": "cafe",
            "type_ids": [
                "cafe",
                "coffee_shop",
                "north_indian_restaurant",
                "restaurant"
            ],
            "address": "205, Tansen Marg, Opp. FICCI Auditorium, Todermal Road Area, Mandi House, New Delhi, Delhi 110001, India",
            "open_state": "Open \u00b7 Closes 9:30\u202fPM",
            "hours": "Open \u00b7 Closes 9:30\u202fPM",
            "operating_hours": {
                "monday": "10\u202fAM\u20139:30\u202fPM",
                "tuesday": "10\u202fAM\u20139:30\u202fPM",
                "wednesday": "10\u202fAM\u20139:30\u202fPM",
                "thursday": "10\u202fAM\u20139:30\u202fPM",
                "friday": "10\u202fAM\u20139:30\u202fPM",
                "saturday": "10\u202fAM\u20139:30\u202fPM",
                "sunday": "10\u202fAM\u20139:30\u202fPM"
            },
            "phone": "+91 99715 66904",
            "website": "https://redcedarhospitality.com/",
            "description": "Quaint North Indian cafe with a terrace. Small, light-filled cafe with a terrace & a selection of North Indian snacks, curries & thalis.",
            "extensions": [
                {
                    "service_options": [
                        "Outdoor seating",
                        "No-contact delivery",
                        "Delivery",
                        "Onsite services",
                        "Takeout",
                        "Dine-in"
                    ]
                },
                {
                    "highlights": [
                        "Great coffee",
                        "Great dessert",
                        "Great tea selection",
                        "Live performances",
                        "Rooftop seating"
                    ]
                },
                {
                    "popular_for": [
                        "Breakfast",
                        "Lunch",
                        "Dinner",
                        "Solo dining",
                        "Good for working on laptop"
                    ]
                },
                {
                    "accessibility": [
                        "Wheelchair accessible parking lot"
                    ]
                },
                {
                    "offerings": [
                        "Coffee",
                        "Healthy options",
                        "Organic dishes",
                        "Quick bite",
                        "Small plates",
                        "Vegan options",
                        "Vegetarian options"
                    ]
                },
                {
                    "dining_options": [
                        "Breakfast",
                        "Brunch",
                        "Lunch",
                        "Dinner",
                        "Dessert",
                        "Seating",
                        "Table service"
                    ]
                },
                {
                    "amenities": [
                        "Restroom"
                    ]
                },
                {
                    "atmosphere": [
                        "Casual",
                        "Cozy",
                        "Quiet",
                        "Romantic",
                        "Trendy",
                        "Upscale"
                    ]
                },
                {
                    "crowd": [
                        "College students",
                        "Groups",
                        "Tourists"
                    ]
                },
                {
                    "planning": [
                        "Brunch reservations recommended",
                        "Lunch reservations recommended",
                        "Accepts reservations",
                        "Usually a wait"
                    ]
                },
                {
                    "payments": [
                        "Credit cards",
                        "Debit cards",
                        "NFC mobile payments"
                    ]
                },
                {
                    "children": [
                        "Good for kids"
                    ]
                },
                {
                    "parking": [
                        "Paid parking lot",
                        "Paid street parking",
                        "Usually plenty of parking"
                    ]
                }
            ],
            "unsupported_extensions": [
                {
                    "accessibility": [
                        "Wheelchair accessible entrance"
                    ]
                }
            ],
            "service_options": {
                "dine_in": true,
                "takeout": true,
                "no_contact_delivery": true
            },
            "order_online": "https://www.google.com/searchviewer/42?cvd=CLw_EicKJeICIjIgEhkiF9LX29IPEQoNL2cvMTFiY2Yyc3BwNxgAOgMI8A0%3D&hl=en-US&gl=us&fo_m=MfohQo559jFvMUOzJVpjPL1YMfZ3bInYwBDuMfaXTPp5KXh-&utm_source=tactile&gei=hqL4aYnhBpuywt0Pm_WU6AU&ei=hqL4aYnhBpuywt0Pm_WU6AU&fo_s=OA,SOE&opi=79508299&ebb=1&cs=0&foub=mcpp",
            "user_review": "\"A calm, composed, cosy, and serene caf\u00e9\u2014open to nature and art.\"",
            "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHb1_LEwJlqET-Ytuh2gziBKDazhFuvXpVo7DLGt4lWpMfcOGdgx1rVjM-AoXD5hRyeLapK7h1es65EGzek-r81UJXSlWaWb-1VO6CnB2GbNWM7HxnGGM3VWRPZgI4GsHY3J6KYBg=w1000-h1000-c-n",
            "serpapi_thumbnail": "https://serpapi.com/images/url/h1tswnicHcRLcoIwAADQE0WIKDidcQGFhvJRq5VANx2IMammSSShKjfsEXqbzvgW7--XW6vNk-MI7k2YUkzQwdCeKGmptBOivh2mDSAGGCfcrN7OYdrBzyK5ZuKSvIPGDnzKxq8oj9uRvww_ta5UEBfIzgTW5ZGs0YHdYF-dShCqOp7z7Z0Wrc4DDqnx5wka6Rn0C7jP6p3ALe4ArNb-s4ymqFvhMkhvEqHSq_B288FeZ8ikjZf5eROx5RW6rgv4YwLkP-puRC0"
        },
        {
            "position": 2,
            "title": "Nobby's Cafe",
            "place_id": "ChIJF54_T7kDDTkRpl26JrYkmLM",
            "data_id": "0x390d03b94f3f9e17:0xb39824b626ba5da6",
            "data_cid": "12941133894001515942",
            "reviews_link": "https://serpapi.com/search.json?data_id=0x390d03b94f3f9e17%3A0xb39824b626ba5da6&engine=google_maps_reviews&hl=en",
            "photos_link": "https://serpapi.com/search.json?data_id=0x390d03b94f3f9e17%3A0xb39824b626ba5da6&engine=google_maps_photos&hl=en",
            "gps_coordinates": {
                "latitude": 28.642889999999998,
                "longitude": 77.175175
            },
            "place_id_search": "https://serpapi.com/search.json?engine=google_maps&google_domain=google.com&hl=en&place_id=ChIJF54_T7kDDTkRpl26JrYkmLM",
            "provider_id": "/g/11wvb3_2qq",
            "rating": 4.9,
            "reviews": 603,
            "type": "Cafe",
            "types": [
                "Cafe"
            ],
            "type_id": "cafe",
            "type_ids": [
                "cafe"
            ],
            "address": "Ground Floor, 9/29, Block 9, East Patel Nagar, Patel Nagar, New Delhi, Delhi 110008, India",
            "open_state": "Open \u00b7 Closes 11\u202fPM",
            "hours": "Open \u00b7 Closes 11\u202fPM",
            "operating_hours": {
                "monday": "8\u202fAM\u201311\u202fPM",
                "tuesday": "8\u202fAM\u201311\u202fPM",
                "wednesday": "8\u202fAM\u201311\u202fPM",
                "thursday": "8\u202fAM\u201311\u202fPM",
                "friday": "8\u202fAM\u201312\u202fAM",
                "saturday": "8\u202fAM\u201312\u202fAM",
                "sunday": "8\u202fAM\u201311\u202fPM"
            },
            "website": "https://www.instagram.com/nobbyscafe/",
            "extensions": [
                {
                    "from_the_business": [
                        "Identifies as women-owned"
                    ]
                },
                {
                    "service_options": [
                        "No-contact delivery",
                        "Delivery",
                        "Takeout",
                        "Dine-in"
                    ]
                },
                {
                    "highlights": [
                        "Great coffee",
                        "Great dessert"
                    ]
                },
                {
                    "popular_for": [
                        "Breakfast",
                        "Lunch",
                        "Solo dining",
                        "Good for working on laptop"
                    ]
                },
                {
                    "offerings": [
                        "Coffee",
                        "Happy hour food",
                        "Healthy options",
                        "Late-night food",
                        "Prepared foods",
                        "Quick bite",
                        "Small plates",
                        "Vegan options",
                        "Vegetarian options"
                    ]
                },
                {
                    "dining_options": [
                        "Breakfast",
                        "Brunch",
                        "Lunch",
                        "Dinner",
                        "Dessert",
                        "Seating",
                        "Table service"
                    ]
                },
                {
                    "amenities": [
                        "Bar onsite",
                        "Restroom",
                        "Wi-Fi",
                        "Free Wi-Fi"
                    ]
                },
                {
                    "atmosphere": [
                        "Casual",
                        "Cozy",
                        "Trendy"
                    ]
                },
                {
                    "crowd": [
                        "Family-friendly",
                        "Groups",
                        "LGBTQ+ friendly"
                    ]
                },
                {
                    "planning": [
                        "Accepts reservations"
                    ]
                },
                {
                    "payments": [
                        "Credit cards",
                        "Debit cards",
                        "NFC mobile payments"
                    ]
                },
                {
                    "children": [
                        "Good for kids",
                        "Kids' menu"
                    ]
                },
                {
                    "parking": [
                        "Free street parking",
                        "Usually plenty of parking",
                        "Valet parking"
                    ]
                }
            ],
            "service_options": {
                "dine_in": true,
                "takeout": true,
                "no_contact_delivery": true
            },
            "reserve_a_table": "https://www.google.com/maps/reserve/v/dine/c/WnxTeb1gONA?source=pa&opi=79508299&hl=en-US&gei=hqL4aYnhBpuywt0Pm_WU6AU&sourceurl=https://www.google.com/search?q%3Dcafes%26pb%3D!4m8!1m3!1d39403.4525504437!2d77.209!3d28.6139!3m2!1i1920!2i1080!4f13.1!7i20!10b1!12m49!1m5!18b1!30b1!31m1!1b1!34e1!2m4!5m1!6e2!20e3!39b1!6m22!49b1!63m0!66b1!74i150000!85b1!91b1!114b1!149b1!178b1!206b1!209b1!212b1!223b1!232b1!234b1!244b1!246b1!250b1!253b1!258b1!260b1!266b1!10b1!12b1!13b1!14b1!16b1!17m1!3e1!20m3!5e2!6b1!14b1!46m1!1b0!96b1!99b1!19m4!2m3!1i360!2i120!4i8!20m57!2m2!1i203!2i100!3m2!2i4!5b1!6m6!1m2!1i86!2i86!1m2!1i408!2i240!7m33!1m3!1e1!2b0!3e3!1m3!1e2!2b1!3e2!1m3!1e2!2b0!3e3!1m3!1e8!2b0!3e3!1m3!1e10!2b0!3e3!1m3!1e10!2b1!3e2!1m3!1e10!2b0!3e4!1m3!1e9!2b1!3e2!2b1!9b0!15m8!1m7!1m2!1m1!1e2!2m2!1i195!2i195!3i20!22m6!1sGF4QdOZz7bylv_ah8OSSiZnBk8txQkY:2!2s1i:0,t:11886,p:GF4QdOZz7bylv_ah8OSSiZnBk8txQkY:2!7e81!12e5!17sGF4QdOZz7bylv_ah8OSSiZnBk8txQkY:44!18e15!24m107!1m28!13m9!2b1!3b1!4b1!6i1!8b1!9b1!14b1!20b1!25b1!18m17!3b1!4b1!5b1!6b1!13b1!14b1!17b1!21b1!22b1!27m1!1b0!28b0!32b1!33m1!1b1!34b1!36e2!10m1!8e3!11m1!3e1!14m1!3b0!17b1!20m2!1e3!1e6!24b1!25b1!26b1!27b1!29b1!30m1!2b1!36b1!37b1!39m3!2m2!2i1!3i1!43b1!52b1!54m1!1b1!55b1!56m1!1b1!61m2!1m1!1e1!65m5!3m4!1m3!1m2!1i224!2i298!72m22!1m8!2b1!5b1!7b1!12m4!1b1!2b1!4m1!1e1!4b1!8m10!1m6!4m1!1e1!4m1!1e3!4m1!1e4!3sother_user_google_review_posts__and__hotel_and_vr_partner_review_posts!6m1!1e1!9b1!89b1!98m3!1b1!2b1!3b1!103b1!113b1!114m3!1b1!2m1!1b1!117b1!122m1!1b1!126b1!127b1!26m4!2m3!1i80!2i92!4i8!30m28!1m6!1m2!1i0!2i0!2m2!1i530!2i1080!1m6!1m2!1i1870!2i0!2m2!1i1920!2i1080!1m6!1m2!1i0!2i0!2m2!1i1920!2i20!1m6!1m2!1i0!2i1060!2m2!1i1920!2i1080!34m19!2b1!3b1!4b1!6b1!8m6!1b1!3b1!4b1!5b1!6b1!7b1!9b1!12b1!14b1!20b1!23b1!25b1!26b1!31b1!37m1!1e81!42b1!49m10!3b1!6m2!1b1!2b1!7m2!1e3!2b1!8b1!9b1!10e2!50m3!2e2!3m1!3b1!61b1!67m5!7b1!10b1!14b1!15m1!1b0!69i767!77b1%26tbm%3Dmap%26hl%3Den",
            "order_online": "https://www.google.com/searchviewer/42?cvd=CLw_EicKJeICIjIgEhkiF9LX29IPEQoNL2cvMTF3dmIzXzJxcRgBOgMI8A0%3D&hl=en-US&gl=us&fo_m=MfohQo559jFvMUOzJVpjPL1YMfZ3bInYwBDuMfaXTPp5KXh-&utm_source=tactile&gei=hqL4aYnhBpuywt0Pm_WU6AU&ei=hqL4aYnhBpuywt0Pm_WU6AU&fo_s=OA,SOE&opi=79508299&orderType=1&ebb=1&cs=0&foub=mcpp",
            "user_review": "\"A cozy little spot with a warm ambiance, great coffee, and friendly service.\"",
            "thumbnail": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH0wcQpRLDlCxXChSmAoQfs69X6HKioQeyZ_EPyY82ZWGBB8qoU3OIdhWoNAfOEfaYZWzEHeuhd9aC4_RqnNJke6ybTTw39smVRAZ7Cec6GZcBHZZ3LL9UpboRAWNWgZnGxwhrSfeiQiZlN=w1000-h1000-c-n",
            "serpapi_thumbnail": "https://serpapi.com/images/url/EmeUeXicHcTLjoIwFADQL0JwMCiTuChIQCXV4qN6N0ZroUToRYtB_EnX8zeTeBbn76PatjG_tl0pd1AgFpV8GvkQqFup24HA2i4aYwljGZusKbuRxOkEa7J0VoWvQ6g2NUGWG88_eMmyRCZ7OEXr_jj5AR4HweSOO3c1vyqOlOSrKD8fgb-jRD7V1T-Ho1N213Rxk15_2W471zf1PiMwDqXwYhBBAuCmqb9rLpgRTnkBOn516rHJZclKqOi0GzqOY6nvwtL_p9NH0A"
        },
        {
            "position": 3,
            "title": "Cafe Lota",
            "place_id": "ChIJP_oFxSfjDDkRG_HG59ndSus",
            "data_id": "0x390ce327c505fa3f:0xeb4addd9e7c6f11b",
            "data_cid": "16954607675155869979",
            "reviews_link": "https://serpapi.com/search.json?data_id=0x390ce327c505fa3f%3A0xeb4addd9e7c6f11b&engine=google_maps_reviews&hl=en",
            "photos_link": "https://serpapi.com/search.json?data_id=0x390ce327c505fa3f%3A0xeb4addd9e7c6f11b&engine=google_maps_photos&hl=en",
            "gps_coordinates": {
                "latitude": 28.6136111,
                "longitude": 77.24249999999999
            },
            "place_id_search": "https://serpapi.com/search.json?engine=google_maps&google_domain=google.com&hl=en&place_id=ChIJP_oFxSfjDDkRG_HG59ndSus",
            "provider_id": "/g/1pp2xb0fh",
            "rating": 4.4,
            "reviews": 4538,
            "price": "$$",
            "extracted_price": null,
            "type": "Cafe",
            "types": [
                "Cafe",
                "Breakfast restaurant",
                "Coffee shop",
                "North Indian restaurant",
                "Restaurant",
                "South Indian restaurant"
            ],
            "type_id": "cafe",
            "type_ids": [
                "cafe",
                "breakfast_restaurant",
                "coffee_shop",
                "north_indian_restaurant",
                "restaurant",
                "south_indian_restaurant"
            ],
            "address": "Gate No. 5, National Crafts Museum, Bhairon Marg, Pragati Maidan, New Delhi, Delhi 110001, India",
            "open_state": "Open \u00b7 Closes 9:30\u202fPM",
            "hours": "Open \u00b7 Closes 9:30\u202fPM",
            "operating_hours": {
                "monday": "8\u202fAM\u20139:30\u202fPM",
                "tuesday": "8\u202fAM\u20139:30\u202fPM",
                "wednesday": "8\u202fAM\u20139:30\u202fPM",
                "thursday": "8\u202fAM\u20139:30\u202fPM",
                "friday": "8\u202fAM\u20139:30\u202fPM",
                "saturday": "8\u202fAM\u20139:30\u202fPM",
                "sunday": "8\u202fAM\u20139:30\u202fPM"
            },
            "phone": "+91 78389 60787",
            "website": "https://redcedarhospitality.com/",
            "description": "Indian cafe on a crafts museum complex. This stylish cafe in a crafts museum offers modern, regional Indian dishes & cookery classes.",
            "extensions": [
                {
                    "service_options": [
                        "Outdoor seating",
                        "No-contact delivery",
                        "Delivery",
                        "Onsite services",
                        "Takeout",
                        "Dine-in"
                    ]
                },
                {
                    "highlights": [
                        "Great coffee",
                        "Great dessert",
                        "Great tea selection",
                        "Sports"
                    ]
                },
                {
                    "popular_for": [
                        "Breakfast",
                        "Lunch",
                        "Dinner",
                        "Solo dining",
                        "Good for working on laptop"
                    ]
                },
                {
                    "accessibility": [
                        "Wheelchair accessible entrance",
                        "Wheelchair accessible parking lot",
                        "Wheelchair accessible restroom",
                        "Wheelchair accessible seating"
                    ]
                },
                {

In [ ]:
def get_serpapi_client():
    return serpapi.Client({
        "api_key": SERP_API_KEY
        })

def search_google_maps(query, lat, lon, zoom):
    client = get_serpapi_client()
    results = client.search({
        "engine": "google_maps",
        "q": query,
        "ll": f"@{lat}, {lon},{zoom}z"
    })
    return results

In [ ]:
import pandas as py
from dotenv import load_dotenv
import os

load_dotenv()



CATEGORIES = [
    "restaurants",
    "cafes",
    "tourist attractions",
    "museums",
    "parks"
]

CITIES = [
    ("Delhi", 28.6139, 77.2090),
    ("Mumbai", 19.0760, 72.8777),
    ("Bangalore", 12.9716, 77.5946),
    ("Jaipur", 26.9124, 75.7873),
    ("Goa", 15.2993, 74.1240),
    ("Chandigarh", 30.7333, 76.7794),
    ("Hyderabad", 17.3850, 78.4867),
    ("Kolkata", 22.5726, 88.3639),
    ("Pune", 18.5204, 73.8567),
    ("Ahmedabad", 23.0225, 72.5714),

    # Add global cities for generalization
    ("New York", 40.7128, -74.0060),
    ("London", 51.5074, -0.1278),
    ("Paris", 48.8566, 2.3522),
    ("Tokyo", 35.6762, 139.6503),
    ("Dubai", 25.2048, 55.2708),
    ("Singapore", 1.3521, 103.8198),
    ("Sydney", -33.8688, 151.2093),
    ("Toronto", 43.6532, -79.3832),
    ("Berlin", 52.5200, 13.4050),
    ("Bangkok", 13.7563, 100.5018),
]

import requests
import time
import random

API_KEY = os.getenv("SERP_API_KEY")
BASE_URL = "https://serpapi.com/search"

CALL_DELAY = 2.0  # seconds (safe buffer)
MAX_CALLS = 200

# i/p params:



def build_ll(lat, lon, zoom=14):
    return f"@{lat},{lon},{zoom}z"

def fetch_places(query, lat, lon, start=0):

    params = {
        "engine": "google_maps",
        "q": query,
        "ll": build_ll(lat, lon),
        "start": start,
        "api_key": API_KEY
    }

    response = requests.get(BASE_URL, params=params)

    if response.status_code != 200:
        print("Error:", response.status_code, response.text)
        return None

    return response.json()

seen_place_ids = set()

def filter_new_places(results):
    new_places = []

    for place in results.get("local_results", []):
        pid = place.get("place_id")
        if pid and pid not in seen_place_ids:
            seen_place_ids.add(pid)
            new_places.append(place)

    return new_places

def collect_data():

    all_results = []
    call_count = 0

    for city, lat, lon in CITIES:
        for category in CATEGORIES:

            for start in [0, 20]:  # pagination

                if call_count >= MAX_CALLS:
                    return all_results

                print(f"Fetching {category} in {city}, page {start}")

                results = fetch_places(category, lat, lon, start)

                if not results:
                    continue

                new_places = filter_new_places(results)

                all_results.extend([
                    {
                        "city": city,
                        "category_query": category,
                        "data": place
                    }
                    for place in new_places
                ])

                call_count += 1

                # rate limiting
                time.sleep(CALL_DELAY + random.uniform(0.2, 0.8))

                if len(new_places) < 5:
                    break  # low yield → stop pagination

    return all_results

import json

data = collect_data()

with open("places_raw.json", "w") as f:
    json.dump(data, f, indent=2)